### ISSUE TITLE
Travel activities labeling

### ISSUE THREAD

**Issue by stefano-polo** [RobertoCorti/gptravel#21]
## Current Status:
Currently, the app displays the labels of travel activities that have a probability greater than 0.5, which is functioning as intended.

## Expected Behavior:
However, when a travel activity does not have any label with a probability greater than 0.5, the app should print the argmax label instead to provide more accurate information to the users.

**Comment by RobertoCorti** [comment]
https://github.com/RobertoCorti/gptravel/tree/feature/issue-21-travel-activities-labeling
