### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by scaraliu** [RobertoCorti/gptravel#27]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://gptravel-prototype.streamlit.app/robertocorti/gptravel/main/Home.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by RobertoCorti** [comment]
Hey 👋 
Thanks for reaching out to us. We were inactive for a while in this project. I just rebooted the app on streamlit. 

Cheers
